stages:
  - build
  - test

build_pdfcpu:
  image: debian:12-slim
  stage: build
  script:
    - apt update
    - apt install -y wget git
    - cd /
    - wget 'https://go.dev/dl/go1.22.1.linux-amd64.tar.gz'
    - tar xzf go1.22.1.linux-amd64.tar.gz
    - cd /root
    - git clone https://github.com/pdfcpu/pdfcpu
    - cd pdfcpu/cmd/pdfcpu
    - /go/bin/go install
    - /root/go/bin/pdfcpu version
    - cp /root/go/bin/pdfcpu $CI_PROJECT_DIR/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/pdfcpu
  tags:
      - shared

.test_template:
  stage: test
  cache:
    untracked: false
    paths:
      - $COMPOSER_HOME/cache
  artifacts:
    expire_in: 1 hour
    name: "$CI_PROJECT_PATH_SLUG-$CI_PIPELINE_ID"
    paths:
      - build/coverage
      - build/doc
  variables:
    COMPOSER_HOME: "$CI_PROJECT_DIR/build/.composer"
  script:
    - cp $CI_PROJECT_DIR/pdfcpu /usr/bin/pdfcpu
    - apk add --no-cache --update pdftk
    - php-ext.sh enable 'xdebug'
    - composer install --no-progress
    - phpcs $CI_PROJECT_DIR/src $CI_PROJECT_DIR/tests --standard=PSR2
    - php vendor/bin/phpunit $CI_PROJECT_DIR/tests --coverage-text -vv --colors=never
    - sami update sami.php
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  tags:
    - shared

test_php71:
    extends: .test_template
    image: $CI_REGISTRY/docker/alpine37-php71:v2

test_php72:
    extends: .test_template
    image: $CI_REGISTRY/docker/alpine38-php72:v1
