language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly
before_script:
  - sudo apt-get update
  - sudo apt-get install -y pdftk
  - composer install
matrix:
  allow_failures:
    - php: nightly